server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.tt.mj: debug
mj:
  task-store:
    # redis || in_memory
    type: in_memory
    timeout: 30d
  translate-way: null
  #百度翻译配置
  baidu-translate:
    appid: ""
    app-secret: ""
  #代理配置
  proxy:
    host: 127.0.0.1
    port: 32345

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mj?serverTimezone=UTC
      username: root
      password: 123456
  redis:
    database: 4
    # Redis服务器地址
    host: 172.16.88.71
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: lxhpredis
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000
