server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.tt.mj: debug
mj:
  translate-way: null
  #百度翻译配置
  baidu-translate:
    appid: ""
    app-secret: ""

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mj?serverTimezone=UTC
      username: root
      password: 123456
